language: go

go:
    - "1.11.2"
    - "1.11.x"
    - "1.x"
    - master

before_install:
    - go get -t -v github.com/fatih/color

script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)
